Update merge-json-files.yml

diff --git a/.github/workflows/merge-json-files.yml b/.github/workflows/merge-json-files.yml
--- a/.github/workflows/merge-json-files.yml
+++ b/.github/workflows/merge-json-files.yml
@@ -32,6 +32,8 @@ jobs:
         echo "Merging favs/*.json..."
         jq -s 'add' favs/*.json > favsr/merged.json || { echo "Error merging favs/*.json"; exit 1; } # Add error checking
         echo "JSON files merged."
+        jq -s 'add' anime/*.json > animer/merged.json || { echo "Error merging favs/*.json"; exit 1; } # Add error checking
+        echo "JSON files merged."
 
     - name: Commit merged files
       run: |
